### ISSUE TITLE
models api methods Promise-based

### ISSUE THREAD

**Issue by jurgob** [d-oliveros/isomorphine#6]
You would love to use promise instead of callbacks.
maybe, to keep it compatible with the previous versions it could be something like

```
User.promises.create({ title: 'Hi there!' }, 'whatever')
.then((err, user, anotherVal) => {
  console.log('Function called directly. No routing or serialization happened.');
});
```
adding the promise base methods in the "promises" value, so you can still use the callback approach

**Comment by d-oliveros** [comment]
Hi @jurgob!

Actually support for promises is one of those undocumented hidden features. I haven't updated the README.md, but since version `8.x.x` I've added support for promises. If your isomorphic method returns a promise, isomorphine will respect it and wait until the request is resolved to resolve the value. See https://github.com/d-oliveros/isomorphine/issues/3.
